# Generated by Django 5.2.7 on 2025-10-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='powerbi_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
