# Generated by Django 5.2.7 on 2025-10-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_powerbi_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='report_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
