# Generated by Django 5.2.7 on 2025-10-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dashboard_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='report_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
