# Generated by Django 5.2.7 on 2025-10-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dashboard_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='workspace_id',
            field=models.CharField(default='...', max_length=200),
            preserve_default=False,
        ),
    ]
