# Generated by Django 5.2.7 on 2025-10-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dashboard_workspace_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='embed_url',
        ),
    ]
