# Generated by Django 5.2.7 on 2025-11-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usuariodashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioDashboard',
        ),
    ]
